# Generated by Django 5.1.6 on 2025-02-27 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pic/')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skin_concern', models.CharField(max_length=100)),
                ('skin_type', models.CharField(max_length=50)),
                ('breakout_frequency', models.CharField(max_length=50)),
                ('reaction_to_skincare', models.CharField(max_length=100)),
                ('redness_inflammation', models.CharField(max_length=100)),
                ('sunscreen_usage', models.CharField(max_length=100)),
                ('skin_conditions', models.CharField(max_length=100)),
                ('after_washing_skin_feel', models.CharField(max_length=100)),
                ('water_intake', models.CharField(max_length=50)),
                ('dark_spots_pigmentation', models.CharField(max_length=100)),
                ('visible_pores', models.CharField(max_length=100)),
                ('exfoliation_frequency', models.CharField(max_length=50)),
                ('fine_lines_wrinkles', models.CharField(max_length=100)),
                ('dairy_processed_food_intake', models.CharField(max_length=100)),
                ('skincare_routine', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
